# Generated by Django 5.1.5 on 2025-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
