# Generated by Django 5.1.5 on 2025-01-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friends_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], max_length=6),
        ),
    ]
