# Generated by Django 5.1.5 on 2025-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friends_dob_alter_friends_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='avater',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=6),
        ),
    ]
